.TH libpinch 3 "10-mar-2021" "version 1.0" "subroutine"
.SH NAME
libpinch \- A C++ library for asynchronous SSH communication
.SH NOTE
See HTML pages for more up-to-date documentation. E.g. at
\fIhttps://www.hekkelman.com/libpinch-doc/\fR or the documentation
installed at your local disk.
.SH DESCRIPTION
This library provides asynchronous SSH for use in client applications.
The history of this code goes back to somewhere around the year 2000
when SFTP support was added to the text editor Pepper. Soon after this
Pepper got a cousin, an SSH terminal application named Salt. And then
a pinch of this Salt was put it into a library aptly named libpinch.
.SH BUGS
Undoubtedly libpinch will contain bugs. Please report any bug you find to maarten@hekkelman.com
